#!/usr/bin/env bash
# This script pings the network specified in the command line argument
if [ "$#" -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
elif [ "$#" -eq 1 ]
then	
	ping "$1" -c 5
fi
