#!/usr/bin/env bash
# this script displays content of the current directory in a list format with only the part of the name afte the first dash. Use for loop. Do not display hidden files.

for file in *
do
	echo "$file" | cut -d'-' -f2
done
