#!/usr/bin/env bash
# this script displays information about the `school` file

FILE="school"

if [ -e "$FILE" ]
then 
	echo "school file exists"
	if [ ! -e "$FILE" ]
	then
		echo "school file is empty"
	else
		echo "shool file is not empty"
	fi
	if [ -f "$FILE" ]
	then
		echo "school file is a regular file"
	fi
else
	echo "school file does not exist"
fi
